first version
CPP-KT/shared_ptr_task pull request #10
Opened 2020-09-28 09:04 UTC by zloilya

2020-09-28 10:38 UTC, Dogzik requested changes
А ещё стоит поразносить код по файлам, ибо нет никаких причин им всем лежать скопом в одном

2020-09-28 10:38 UTC, Dogzik commented on shared_ptr.h
> +            : cb(nullptr), ptr(nullptr) {}
Почему бы просто не перевызвать дефольный конструктор вместо копипасты?

2020-09-28 10:38 UTC, Dogzik commented on shared_ptr.h
> +    }
Можно не копировать код, а просто перевызвать конструктор ниже. Возможно логику с `default_delete` по умолчанию стоит реализовывать в `*_ptr`, а не контрол блоках

2020-09-28 10:38 UTC, Dogzik commented on shared_ptr.h
> +            cb  = new cb_ptr<U, D>(new_ptr, deleter);
Почему бы не промувать тут `deleter`?

2020-09-28 10:38 UTC, Dogzik commented on shared_ptr.h
> +        return cb->use_count();
[minor] Почему бы не использовать тут тернарник?

2020-09-28 10:38 UTC, Dogzik commented on shared_ptr.h
> +        shared_ptr().swap(*this);
Кажется ты лишний раз уменьшаешь счётчик, ибо `shared_ptr`, с которым ты свапнулся его уменьшит при смерти

2020-09-28 10:38 UTC, Dogzik commented on shared_ptr.h
> +        shared_ptr(_ptr).swap(*this);
Кажется ты лишний раз уменьшаешь счётчик, ибо `shared_ptr`, с которым ты свапнулся его уменьшит при смерти

2020-09-28 10:38 UTC, Dogzik commented on shared_ptr.h
> +    }
Кажется ты лишний раз уменьшаешь счётчик, ибо `shared_ptr`, с которым ты свапнулся его уменьшит при смерти

2020-09-28 10:38 UTC, Dogzik commented on shared_ptr.h
> +        shared_ptr(_ptr).swap(*this);
А ещё почему бы просто не перевызвать правильно перегрузку ниже?

2020-09-28 10:38 UTC, Dogzik commented on shared_ptr.h
> +    }
Зачем эти функции делать `friend`, если можно просто вызывать `get()`?

2020-09-28 10:38 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr(U* new_ptr) {
Будет довольно неловко, когда у тебя из сырого указателся НЕЯВНО получится шареный и удалит тебе его

2020-09-28 14:41 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr(U* new_ptr) {
Всё ещё возможно НЕЯВНО создать `shared_ptr` от сырого указателся

2020-09-28 14:42 UTC, Dogzik requested changes

2020-09-28 14:42 UTC, Dogzik commented on control_blocks.h
> +};
Перенос в конце файла

2020-09-28 14:42 UTC, Dogzik commented on shared_ptr.h
>          shared_ptr(_ptr, _d).swap(*this);
Зачем коировать `_d`?

2020-09-28 16:26 UTC, zloilya commented on shared_ptr.h
> +    shared_ptr(U* new_ptr) {
не понимаю как от сырых указателей защищаться...

2020-09-28 16:38 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr(U* new_ptr) {
`explicit`

2020-09-30 11:41 UTC, Dogzik approved these changes

2020-09-30 11:42 UTC, Dogzik commented
Не понял в чём глубинный смысл последнего коммита. Не всегда обязательно 1 в 1 обводить cppref

2020-09-30 11:42 UTC, closed without merging