Лемешкова Наталья М3337
CPP-KT/shared_ptr_task pull request #14
Opened 2020-09-29 11:01 UTC by Natallem

2020-10-03 21:56 UTC, Dogzik requested changes

2020-10-03 21:56 UTC, Dogzik commented on control_block.h
> +    D deleter;
Если `D` - пустой класс, который лишь содержит оператор `()`, то он будет занимать место в твоём классе, хотя в этом нет смысла. Избедать этого можно с помощью [этой оптимизации](https://en.cppreference.com/w/cpp/language/ebo)

2020-10-03 21:56 UTC, Dogzik commented on shared_ptr.h
> +    };
* Зачем копировать `deleter`?
* Если вылетит исключение при создании блока, то ты не вызовешь делетер от переданного указателя, хотя нужно

2020-10-03 21:56 UTC, Dogzik commented on shared_ptr.h
> +        set_fields_and_add_ref(r.ptr, r.c_block);
Можно пожалуства не экономить на фигурных скобках?

2020-10-03 21:56 UTC, Dogzik commented on shared_ptr.h
> +    long use_count() const noexcept {
Снова вопрос про `long`

2020-10-03 21:56 UTC, Dogzik commented on shared_ptr.h
> +            swap(r);
[minor] А почему бы не поступить аналогично `copy_assignment_operator`?

2020-10-03 21:56 UTC, Dogzik commented on control_block.h
> +    void try_delete_object() {
Почему бы не унести это просто в `release_ref`?

2020-10-03 21:56 UTC, Dogzik commented on shared_ptr.h
> +        if (*this != r) {
Это проверка делает не то, что ты хочешь

2020-10-03 21:56 UTC, Dogzik commented on shared_ptr.h
> +        if (*this != r) {
И если это конструктор то зачем она вообще?

2020-10-03 21:56 UTC, Dogzik commented on shared_ptr.h
> +    friend bool operator==(shared_ptr<U> const &lhs, shared_ptr<V> const &rhs) noexcept;
Зачем ему быть `friend`, если можно реализовать чисто на публичных методах?

2020-10-03 21:56 UTC, Dogzik commented on shared_ptr.h
> +}
Перенос в конце файла

2020-10-03 21:56 UTC, Dogzik commented on shared_ptr.h
> +        shared_ptr<T>(r, d).swap(*this);
Зачем копировать `d`?

2020-10-03 21:56 UTC, Dogzik commented on weak_ptr.h
> +    long use_count() const noexcept {
Снова `long`

2020-10-03 21:56 UTC, Dogzik commented on weak_ptr.h
> +    void swap(weak_ptr &r) noexcept {
Зачем ему быть приватным?

2020-10-03 21:56 UTC, Dogzik commented on weak_ptr.h
> +            swap(r);
А почему бы не поступить аналогично `copy_assignment_operator`?

2020-10-05 17:42 UTC, Dogzik commented on shared_ptr.h
> +    };
Сейчас ты молча съедаешь исключение и пользователь класса ничего не узнаёт о проблеме

2020-10-05 17:49 UTC, Dogzik commented on weak_ptr.h
> +    void swap(weak_ptr &r) noexcept {
Свап всё ещё приватный

2020-10-05 17:55 UTC, Dogzik requested changes
Плюс ответил в старые треды

2020-10-05 17:55 UTC, Dogzik commented on shared_ptr.h
> +        }
Вообще тут не надо бросать исключения, а создавать пустой, судя по цппреф

2020-10-06 10:17 UTC, Natallem commented on shared_ptr.h
> +    };
В стандартном шареде если во время конструктора копирования или (при наличии) move-конструктора вылетает ошибка, то переданный объект не удаляется. Я долго пыталась сделать так, чтобы сначала поймать исключение при создании блока (учитываю оптимизацию, использовала function-try-block), затем пробросить исключение из конструктора шареда в вызывающую функцию, но я не так и не поняла, почему терменирование вызывающей функции не происходит автоматически, в таком случае. В первом коммите можно будет найти, что я пыталась сделать.

Не уверена, могут ли у нас вообще возникнуть ошибки при создании control block'а, кроме как при копировании переданного делитера.

Поэтому по итогу оставила так, как в стандартном шареде. Т.е. если у нас что то не так с классом делитера и он бросает исключение при копировании, я не удаляю объект с помощью этого делитера(вроде бы даже логично, раз он кривой), а просто терминируюсь.

2020-10-06 10:30 UTC, Natallem commented on shared_ptr.h
> +        }
Согласно п.11 ст. (https://en.cppreference.com/w/cpp/memory/shared_ptr/shared_ptr)
"Note that r.lock() may be used for the same purpose: the difference is that this constructor throws an exception if the argument is empty, while std::weak_ptr<T>::lock() constructs an empty std::shared_ptr in that case."

Аналогичное стандартному поведение можно ожидать и при непосредственно проведенной мною проверке:

weak_ptr<int> spoiled_weak(){
    return make_shared<int>(3);
}
std::weak_ptr<int> std_spoiled_weak(){
    return std::make_shared<int>(3);
}

int main(int argc, char **argv) {
    try {
        std::shared_ptr<int> t(std_spoiled_weak());
    } catch (std::bad_weak_ptr & e){
        std::cout << "std caught\n";
    }

    try {
        shared_ptr<int> t(spoiled_weak());
    } catch (std::bad_weak_ptr & e){
        std::cout << "caught\n";
    }
}

2020-10-06 11:40 UTC, Dogzik commented on shared_ptr.h
> +        }
Справедливо, мой косяк

2020-10-06 11:52 UTC, Dogzik commented on shared_ptr.h
> +    };
![image](https://user-images.githubusercontent.com/26696217/95197804-d3105b80-07e2-11eb-83b0-2d9a95035e08.png)
![image](https://user-images.githubusercontent.com/26696217/95197816-dad00000-07e2-11eb-8fa6-0f21084f34f8.png)
Грубо говоря можно считать что конструирование самого `D`, должно быть `noexcept`, иначе UB. А вот вполне реальна ошибка, когда не хватило памяти для вызова `new`

2020-10-06 11:52 UTC, Dogzik requested changes

2020-10-06 11:52 UTC, Dogzik commented on shared_ptr.h
> +        c_block->add_ref();
Отписал про это в старый тред

2020-10-06 14:50 UTC, Natallem commented on shared_ptr.h
> +    };
Поняла, спасибо большое за пояснения!

2020-10-06 14:51 UTC, closed without merging