Implement shared_ptr & weak_ptr
CPP-KT/shared_ptr_task pull request #2
Opened 2020-09-26 16:56 UTC by NH5pml30

2020-09-30 13:52 UTC, hazzus requested changes

2020-09-30 13:52 UTC, hazzus commented on shared_ptr.h
> +    if (cblock->ref_count() == 0)
Лучше будет занести логику, связанную с cblock в сам cblock, а не выполнять махинации из shared/weak ptr

2020-09-30 13:52 UTC, hazzus commented on weak_ptr.h
> +  weak_ptr(weak_ptr<Y> &&other, int) noexcept;
Смотри выше

2020-09-30 14:50 UTC, NH5pml30 commented on control_block.cpp
> +    delete cb;
Я думал delete this выглядит ужасно, но после выноса логики внутрь только так тогда

2020-09-30 14:51 UTC, NH5pml30 commented on control_block.h
> +struct regular_control_block final : control_block
Сделал

2020-09-30 14:51 UTC, NH5pml30 commented on control_block.h
> +regular_control_block<T, Deleter>::regular_control_block(T * ptr, Deleter d) : ptr(ptr), d(d)
Сделал

2020-09-30 14:51 UTC, NH5pml30 commented on shared_ptr.h
> +  explicit shared_ptr(std::nullptr_t);
Сделал

2020-09-30 14:51 UTC, NH5pml30 commented on shared_ptr.h
> +  shared_ptr(const shared_ptr &other) noexcept;
Всё отделил

2020-09-30 14:53 UTC, NH5pml30 commented on shared_ptr.h
> +  shared_ptr(std::nullptr_t, Deleter d);
Не понял, какой конструктор выше?

2020-09-30 14:54 UTC, NH5pml30 commented on shared_ptr.h
> +  explicit shared_ptr(const shared_ptr<Y> &other, T *ptr) noexcept;
Убрал

2020-09-30 14:55 UTC, NH5pml30 commented on shared_ptr.h
> +  shared_ptr & swap(shared_ptr<Y> &other);
Тут был смысл в том что я свапаю указатели разных типов, так что сделал внешнюю функцию темплейтную от двух типов

2020-09-30 14:55 UTC, NH5pml30 commented on control_block.cpp
> +    delete cb;
Копия?

2020-09-30 14:56 UTC, NH5pml30 commented on control_block.h
> +struct regular_control_block final : control_block
Уже ответил

2020-09-30 14:57 UTC, NH5pml30 commented on control_block.h
> +shared_ptr<T> make_shared(Args&&... args);
Сделал публичным окей

2020-09-30 14:57 UTC, NH5pml30 commented on shared_ptr.h
> +  explicit shared_ptr(std::nullptr_t);
Уже ответил

2020-09-30 14:57 UTC, NH5pml30 commented on shared_ptr.h
> +  shared_ptr(std::nullptr_t, Deleter d);
Уже ответил, не понял

2020-09-30 14:57 UTC, NH5pml30 commented on shared_ptr.h
> +  explicit shared_ptr(const shared_ptr<Y> &other, T *ptr) noexcept;
Уже ответил

2020-09-30 15:00 UTC, NH5pml30 commented on shared_ptr.h
> +  shared_ptr(shared_ptr<Y> &&other, int) noexcept;
Есть проблема с копирующими конструкторами (либо мувающими). Если делать копирующий конструктор как часть темплейтного (убрать вообще его объявление), то при его вызове вообще ничего не происходит (даже команд нет). Тогда нужно два отдельных конструктора с одной логикой и копипастой в 4 местах (так как из копирующего темплейтный общий не вызвать) и приходится dummy параметр отправлять. Я не знаю как лучше сделать

2020-09-30 15:01 UTC, NH5pml30 commented on shared_ptr.h
> +  shared_ptr & swap(shared_ptr<Y> &other);
Уже ответил

2020-09-30 15:01 UTC, NH5pml30 commented on shared_ptr.h
> +shared_ptr<T>::shared_ptr(const shared_ptr<Y> &other, int) noexcept : shared_ptr(other.cblock, other.ptr)
Там написал

2020-09-30 15:01 UTC, NH5pml30 commented on shared_ptr.h
> +shared_ptr<T>::shared_ptr(const shared_ptr &other) noexcept : shared_ptr(other, 0)
Ответил выше

2020-09-30 15:01 UTC, NH5pml30 commented on control_block.h
> +regular_control_block<T, Deleter>::regular_control_block(T * ptr, Deleter d) : ptr(ptr), d(d)
Уже ответил

2020-09-30 15:02 UTC, NH5pml30 commented on shared_ptr.h
> +    if (cblock->ref_count() == 0)
Занёс

2020-09-30 15:02 UTC, NH5pml30 commented on weak_ptr.h
> +  weak_ptr(weak_ptr<Y> &&other, int) noexcept;
Да

2020-10-02 17:32 UTC, hazzus commented on shared_ptr.h
> +  shared_ptr(std::nullptr_t, Deleter d);
nullptr спокойно может каститься к Y*, зачем этот конструктор, когда есть от Y*?

2020-10-02 17:34 UTC, hazzus commented on shared_ptr.h
> +  explicit shared_ptr(const shared_ptr<Y> &other, T *ptr) noexcept;
Соре, странно что он дублирует коменты, хотя мне не показал что сохранил

2020-10-02 17:42 UTC, hazzus commented on shared_ptr.h
> +  shared_ptr(shared_ptr<Y> &&other, int) noexcept;
Лучше копипаста, чем такая попытка избавиться от нее, тем более копипаста небольшая

2020-10-02 17:49 UTC, hazzus requested changes
Почти, убери конструкторы с интами, это какой то костыль, лучше копипаста.

2020-10-02 17:52 UTC, NH5pml30 commented on shared_ptr.h
> +  shared_ptr(std::nullptr_t, Deleter d);
Неправда, он не сможет задедьюсить что такое Y

2020-10-02 17:52 UTC, NH5pml30 commented on shared_ptr.h
> +  shared_ptr(std::nullptr_t, Deleter d);
Но зато у меня этот конструктор не то делает...

2020-10-02 17:59 UTC, NH5pml30 commented on shared_ptr.h
> +  shared_ptr(shared_ptr<Y> &&other, int) noexcept;
Окей поправил

2020-10-02 18:02 UTC, NH5pml30 commented on shared_ptr.h
> +  shared_ptr(std::nullptr_t, Deleter d);
Поправил в перенаправление (nullptr_t, Deleter) -> (T *, Deleter)

2020-10-04 15:12 UTC, hazzus approved these changes
Окей, вроде все

2020-10-04 15:13 UTC, closed without merging