tests passed
CPP-KT/shared_ptr_task pull request #3
Opened 2020-09-26 20:08 UTC by pprettysimpple

2020-09-26 21:02 UTC, Dogzik requested changes

2020-09-26 21:02 UTC, Dogzik commented on shared_ptr.h
> +    cblock->add_ref_shared();
То, что `rhs == nullptr` не означает, что у его отсуствует `cblock`

2020-09-26 21:02 UTC, Dogzik commented on shared_ptr.h
> +    cblock->add_ref_shared();
То, что `rhs == nullptr` не означает, что у его отсуствует `cblock`

2020-09-27 07:11 UTC, pprettysimpple commented on control_block.h
> +    D deleter = std::default_delete<T>();
написал атрибут [no_unique_address] для этой цели

2020-09-27 07:11 UTC, pprettysimpple commented on control_block.h
> +        : control_block(), ptr(ptr), deleter(deleter) {}
помувал его в этом месте

2020-09-27 07:11 UTC, pprettysimpple commented on shared_ptr.h
> +    friend shared_ptr<U> make_shared(Args&& ... args);
сделал public

2020-09-27 07:11 UTC, pprettysimpple commented on shared_ptr.h
> +shared_ptr<T>::shared_ptr(Y* p)
сделал try-catch

2020-09-27 07:11 UTC, pprettysimpple commented on shared_ptr.h
> +shared_ptr<T>::shared_ptr(Y* p, D deleter)
сделал try-catch

2020-09-27 07:11 UTC, pprettysimpple commented on shared_ptr.h
> +    return bool(ptr);
сделал `ptr != nullptr`

2020-09-27 07:12 UTC, pprettysimpple commented on shared_ptr.h
> +    cblock->add_ref_shared();
сделал `if`
~~больше ничего не отвалится~~

2020-09-27 07:12 UTC, pprettysimpple commented on shared_ptr.h
> +    cblock->add_ref_shared();
сделал `if`
~~больше ничего не отвалится~~

2020-09-27 07:12 UTC, pprettysimpple commented on shared_ptr.h
> +}
добавил

2020-09-27 07:12 UTC, pprettysimpple commented on control_block.h
> +    ~inplace_control_block() noexcept override = default;
убрал

2020-09-27 07:12 UTC, pprettysimpple commented on control_block.h
> +    ~regular_control_block() noexcept override = default;
убрал

2020-09-27 07:12 UTC, pprettysimpple commented on shared_ptr.h
> +    cblock->add_ref_weak();
сделал `if`
~~больше ничего не отвалится~~

2020-09-27 07:12 UTC, pprettysimpple commented on shared_ptr.h
> +    cblock->add_ref_shared();
поменял `if` на `cblock == nullptr`

2020-09-27 07:12 UTC, pprettysimpple commented on shared_ptr.h
> +    cblock->add_ref_shared();
поменял `if` на `cblock == nullptr`

2020-09-27 11:36 UTC, pprettysimpple commented on control_block.h
> +    D deleter = std::default_delete<T>();
вместо атрибута сделал наследование, потому что не разобрался с принципом работы атрибута

2020-09-27 15:48 UTC, Dogzik commented on shared_ptr.h
> +shared_ptr<T>::shared_ptr(Y* p)
Лучше не копировать код, а просто делегировать работу другому конструктора передав в качестве `D d` экземпляр `std::default_delete<Y>`

2020-09-27 16:25 UTC, Dogzik requested changes

2020-09-27 16:25 UTC, Dogzik commented on shared_ptr.h
> +}
А зачем тут второй своп, если первый уже присвоит в `r` оба указателя в `nullptr`? Может для ясности не стоит вообще тут использовать swap, а оставить их для операторов присваивания?

2020-09-27 16:25 UTC, Dogzik commented on shared_ptr.h
> +    weak_ptr(std::move(rhs)).swap(*this);
Кажется, если `cblock == rhs.cblock`, то счётчик ссылок уменьшится на 1, хотя не должен

2020-09-27 16:25 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr(std::move(rhs)).swap(*this);
Кажется, если `cblock == rhs.cblock`, то счётчик ссылок уменьшится на 1, хотя не должен

2020-09-27 16:25 UTC, Dogzik commented on shared_ptr.h
> +    weak_ptr(rhs).swap(*this);
Очень не очевидно, что при `cblock == rhs.cblock` данный код работает корректно. Судя по комментарию ниже, ты не задумывался от таком случае, так что я хочу пояснений или исправления кода

2020-09-27 16:25 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr(rhs).swap(*this);
Очень не очевидно, что при `cblock == rhs.cblock` данный код работает корректно. Судя по комментарию ниже, ты не задумывался от таком случае, так что я хочу пояснений или исправления кода

2020-09-27 16:25 UTC, Dogzik commented on shared_ptr.h
> +}
Почему мы не делегировать работу другому `reset` вместо копирования кода?

2020-09-27 16:25 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr<T>(p, d).swap(*this);
Зачем тут копировать `d`?

2020-09-27 16:25 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr().swap(rhs);
А зачем тут второй своп, если первый уже присвоит в `rhs` оба указателя в `nullptr`? Может для ясности не стоит вообще тут использовать swap, а оставить их для операторов присваивания?

2020-09-27 17:19 UTC, pprettysimpple commented on shared_ptr.h
> +shared_ptr<T>::shared_ptr(Y* p)
сделал значение по умолчанию для D, ещё и избавился от лишней копипастной функции

2020-09-27 17:19 UTC, pprettysimpple commented on shared_ptr.h
> +    }
сделал так что `dec_ref_*` возвращают `true`, если нужно удалить `cblock`, инкапсулировал некоторую логику внутрь. пометил эти функции `[[nodiscard]]`, потому что игнорировать их возврат очень опасно.

2020-09-27 17:19 UTC, pprettysimpple commented on shared_ptr.h
> +}
сделал без свопов

2020-09-27 17:19 UTC, pprettysimpple commented on shared_ptr.h
> +    weak_ptr(std::move(rhs)).swap(*this);
сделал `if` на равенство

2020-09-27 17:19 UTC, pprettysimpple commented on shared_ptr.h
> +    shared_ptr(std::move(rhs)).swap(*this);
сделал `if` на равенство

2020-09-27 17:20 UTC, pprettysimpple commented on shared_ptr.h
> +    weak_ptr(rhs).swap(*this);
тут в отличии от move_assignment_operator проблемы нет
если контрол-блок один, то счетчик слабых ссылок увеличится на 1 при копировании `rhs`, а потом уменьшится на 1, когда произойдёт разрушение временного объекта, в который мы свопнули `this`

2020-09-27 17:20 UTC, pprettysimpple commented on shared_ptr.h
> +    shared_ptr(rhs).swap(*this);
тут в отличии от move_assignment_operator проблемы нет
если контрол-блок один, то счетчик сильных ссылок увеличится на 1 при копировании `rhs`, а потом уменьшится на 1, когда произойдёт разрушение временного объекта, в который мы свопнули `this`

2020-09-27 17:23 UTC, pprettysimpple commented on shared_ptr.h
> +}
Вовсе убрал эту функцию, сделал для `void reset(Y* rhs, D deleter)` значение по умолчанию. Стало меньше кода

2020-09-27 17:23 UTC, pprettysimpple commented on shared_ptr.h
> +    shared_ptr<T>(p, d).swap(*this);
принял по универсальной ссылке и сделал `std::forward`

2020-09-27 17:23 UTC, pprettysimpple commented on shared_ptr.h
> +    shared_ptr().swap(rhs);
сделал без свопов

2020-09-27 17:29 UTC, pprettysimpple commented on shared_ptr.h
> +    weak_ptr(rhs).swap(*this);
`weak_ptr& operator=( const weak_ptr& r ) noexcept; | (1)`
_1-3) Equivalent to std::weak_ptr<T>(r).swap(*this)_
оригинал: https://en.cppreference.com/w/cpp/memory/weak_ptr/operator%3D

2020-09-27 17:29 UTC, pprettysimpple commented on shared_ptr.h
> +    shared_ptr(rhs).swap(*this);
`shared_ptr& operator=( const shared_ptr& r ) noexcept; | (1)`
1) Shares ownership of the object managed by r. If r manages no object, *this manages no object too. _Equivalent to `shared_ptr<T>(r).swap(*this)`_.
оригинал: https://en.cppreference.com/w/cpp/memory/shared_ptr/operator%3D

2020-09-27 20:13 UTC, Dogzik commented on shared_ptr.h
> +shared_ptr<T>::shared_ptr(Y* p)
Осталось только пометить его `explicit`

2020-09-27 20:19 UTC, Dogzik commented on shared_ptr.h
> +    weak_ptr(std::move(rhs)).swap(*this);
Ты исправил проблемы с `cblock`, однако теперь то, куда `weak_ptr` **указывает** не меняется, хотя долно

2020-09-27 20:19 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr(std::move(rhs)).swap(*this);
Ты исправил проблемы с `cblock`, однако теперь то, куда `shared_ptr` **указывает** не меняется, хотя долно

2020-09-27 20:22 UTC, Dogzik requested changes
Почти готово, почитай ответы на комменты выше

2020-09-27 21:15 UTC, pprettysimpple commented on shared_ptr.h
> +    weak_ptr(std::move(rhs)).swap(*this);
я вроде осознал. мы не хотим уменьшить счетчик ссылок, только когда присваиваем самого в себя. так что если `this != &rhs`, то делаем своп-трик, иначе просто возвращаем себя, потому что это мы и есть.

2020-09-27 21:15 UTC, pprettysimpple commented on shared_ptr.h
> +    shared_ptr(std::move(rhs)).swap(*this);
я вроде осознал. мы не хотим уменьшить счетчик ссылок, только когда присваиваем самого в себя. так что если `this != &rhs`, то делаем своп-трик, иначе просто возвращаем себя, потому что это мы и есть.

2020-09-28 08:47 UTC, Dogzik approved these changes

2020-09-28 08:47 UTC, closed without merging