Initial test passing
CPP-KT/shared_ptr_task pull request #4
Opened 2020-09-26 20:51 UTC by EgorkaZ

2020-09-27 17:10 UTC, Dogzik requested changes
В целом шалит форматирование. Советую воспользоваться каким-то автоформатерром

2020-09-27 17:10 UTC, Dogzik commented on shared_ptr.h
> +}
Перенос в конце файла

2020-09-27 17:10 UTC, Dogzik commented on shared_ptr.h
> +inline shared_ptr<Y> make_shared(Args && ... args)
`inline` для шаблонных функций не делает ничего

2020-09-27 17:10 UTC, Dogzik commented on weak_ptr.h
> +        : m_block(impl::add_weak_or_null(other.m_block))
Зачем тут увеличивать счётчик ссылок?

2020-09-27 17:10 UTC, Dogzik commented on weak_ptr.h
> +        return !m_block || !m_block->counter;
Снова касты вместо сравнений

2020-09-27 17:10 UTC, Dogzik commented on weak_ptr.h
> +        }
Эта проверка тут в прицпе не обязательна

2020-09-27 17:10 UTC, Dogzik commented on weak_ptr.h
> +        }
Эта проверка тут в прицпе не обязательна

2020-09-27 17:10 UTC, Dogzik commented on weak_ptr.h
> +};
Перенос в конце файла

2020-09-27 20:14 UTC, EgorkaZ commented on counting_blocks.h
> +    { return !weak_counter; }
Оно таким задумано

2020-10-01 20:56 UTC, EgorkaZ commented on shared_ptr.h
> +        if (&rhs != this) {
Потому что тогда `counter`>=2
Делаем `--counter` — `counter`>=1 — удаление не происходит

2020-10-01 20:57 UTC, EgorkaZ commented on shared_ptr.h
> +        if (&other != this) {
Тогда `counter`>=2
Делаем `--counter` — `counter`>=1
При муве число объектов сократится на штуку

2020-10-01 21:13 UTC, EgorkaZ commented on weak_ptr.h
> +        }
Она позволяет потом смело вызывать `raw_clear()` и не думать

2020-10-01 22:27 UTC, Dogzik commented on counting_blocks.h
> +    Deleter deleter;
Почему бы просто не отнаследоваться от двух классов?

2020-10-01 22:34 UTC, Dogzik commented on shared_ptr.h
> +    }
Напонми ещё раз чем всё это лучше, например `shared_ptr().swap(*this)`?

2020-10-01 22:49 UTC, Dogzik requested changes
А ещё я не понимаю стойкое желание плодить цепочки мутабельных вызовов вида `a->b->c` и т.д. Как минимум дебагать такие вещи будет неудоно, ибо брейкпоинты ставятся на строчки

2020-10-01 22:49 UTC, Dogzik commented on shared_ptr.h
> +    }
Почему бы просто не перевызвать конструктор ниже вместо копирования кода?

2020-10-01 22:49 UTC, Dogzik commented on shared_ptr.h
> +    }
А чем это лучше `shared_ptr(rhs).swap(*this)`?

2020-10-01 22:49 UTC, Dogzik commented on shared_ptr.h
> +    }
А чем это лучше `shared_ptr(std::move(rhs)).swap(*this)`?

2020-10-01 22:49 UTC, Dogzik commented on shared_ptr.h
> +    return shared_ptr<Y>(static_cast<counting_block*>(block), block->get_ptr());
[note] Касты к базе вполне происходят неявно

2020-10-01 22:49 UTC, Dogzik commented on weak_ptr.h
> +    }
А чем это лучше `weak_ptr(rhs).swap(*this)`?

2020-10-01 22:49 UTC, Dogzik commented on weak_ptr.h
> +    }
А чем это лучше `weak_ptr(std::move(rhs)).swap(*this)`?

2020-10-02 09:36 UTC, EgorkaZ commented on shared_ptr.h
> +    return shared_ptr<Y>(static_cast<counting_block*>(block), block->get_ptr());
В этом случае темплейты делают что-то странное, и оно находит не ту перегрузку. Сделать `static_cast` было проще, чем разобраться, что куда не туда инстанцировалось

2020-10-02 09:38 UTC, EgorkaZ commented on shared_ptr.h
> +    }
Тем, что у меня нет `swap`
Ну и заодно тем, что так на одно конструирование+разрушение меньше

2020-10-02 09:41 UTC, EgorkaZ commented on shared_ptr.h
> +    }
Если я правильно понял вопрос, то потому что там в качестве `counting_block` создаётся чуть `pointing_deleting_block`, который будет оверкиллом, если кастомного делитера нам не передали

2020-10-02 13:05 UTC, Dogzik commented on shared_ptr.h
> +    }
В чём оверкилл, если в нём поддержана empty-base-optimization?

2020-10-02 13:06 UTC, Dogzik commented on shared_ptr.h
> +    }
При этом ты буквально копируешь код конструктора сюда. И shared_ptr двольно дешёвый в копировнии и по размеру в целом

2020-10-02 13:07 UTC, Dogzik commented on shared_ptr.h
> +    return shared_ptr<Y>(static_cast<counting_block*>(block), block->get_ptr());
Я кажется понял, что происходит ок

2020-10-02 18:39 UTC, closed without merging