[hw] shared_ptr task
CPP-KT/shared_ptr_task pull request #5
Opened 2020-09-27 14:23 UTC by lejabque

2020-09-27 19:56 UTC, Dogzik requested changes

2020-09-27 19:56 UTC, Dogzik commented on shared_ptr.h
> +    }
Почему это работает, если `cblock == other.cblock`?

2020-09-27 19:56 UTC, Dogzik commented on shared_ptr.h
> +    }
Почему это работает, если `cblock == other.cblock`?

2020-09-27 19:56 UTC, Dogzik commented on shared_ptr.h
> +  }
Не очегь понятно какой смысо несёт этот оператор, да и в стандартном `weak_ptr` его нет

2020-09-27 20:09 UTC, lejabque commented on control_block.h
> +  typename std::aligned_storage_t<sizeof(T), alignof(T)> data;
fixed, Павел на практике так написал, а оно действительно и не нужно  ¯\_(ツ)_/¯

2020-09-27 20:10 UTC, lejabque commented on control_block.cpp
> +  }
fixed (хотел инвариант n_weak на 1 больше, если есть хотя бы одна сильная) (1)

2020-09-27 20:10 UTC, lejabque commented on shared_ptr.h
> +        ptr(nullptr) {}
fixed

2020-09-27 20:10 UTC, lejabque commented on control_block.cpp
> +  }
fixed (хотел инвариант n_weak на 1 больше, если есть хотя бы одна сильная) (2)

2020-09-27 20:11 UTC, lejabque commented on shared_ptr.h
> +        ptr(nullptr) {}
fixed

2020-09-27 20:15 UTC, lejabque commented on shared_ptr.h
> +  }
Да, убрал ~~(смысл был типа жив ли объект)~~

2020-09-27 20:16 UTC, lejabque commented on shared_ptr.h
> +  }
fixed, забыл убрать, когда перенёс

2020-09-27 20:28 UTC, Dogzik commented on control_block.cpp
> +  n_weak--;
Тест

2020-09-27 20:28 UTC, Dogzik commented on control_block.h
> +  typename std::aligned_storage_t<sizeof(T), alignof(T)> data;
Тест2

2020-09-27 20:30 UTC, Dogzik commented on shared_ptr.h
> +  }
Тест3

2020-09-27 20:30 UTC, Dogzik commented on shared_ptr.h
> +    }
Тест4

2020-09-27 20:34 UTC, Dogzik commented on CMakeLists.txt
> +        test_object.h
Тест5

2020-09-27 20:34 UTC, Dogzik commented on shared_ptr.h
> +    }
Тест6

2020-09-27 20:35 UTC, Dogzik commented on shared_ptr.h
> +    delete cblock;
Тест7

2020-09-27 20:36 UTC, lejabque commented on shared_ptr.h
> +    }
Создается копия (счетчик увеличится на 1), свопается, удаляется созданная копия (счетчик уменьшится на 1). Если копия и своп корректно работают, вроде проблем никаких и не будет.

(или вопрос к тому, что можно проверять равенство и не делать лишних действий?)

2020-09-27 20:36 UTC, lejabque commented on shared_ptr.h
> +    delete cblock;
fixed
![image](https://user-images.githubusercontent.com/30625073/94375153-4bf42100-011a-11eb-9a26-73a89a84db2c.png)

2020-09-27 20:39 UTC, Dogzik requested changes
Жду изменений

2020-09-27 20:53 UTC, lejabque commented on shared_ptr.h
> +      }
Вынес

2020-09-27 21:09 UTC, lejabque commented on shared_ptr.h
> +    }
Понял баг, если контролблоки одинаковые, то нужно только забрать ptr (так как он может быть на "другую часть"), а иначе так.
fixed

2020-09-27 21:09 UTC, lejabque commented on shared_ptr.h
> +    }
Понял баг, если контролблоки одинаковые, то нужно только забрать ptr (так как он может быть на "другую часть"), а иначе так.
fixed

2020-09-27 21:10 UTC, lejabque commented on shared_ptr.h
> +    }
Баг в move assignment пофиксил, а это работает и так нормально при равных блоках

2020-09-27 21:36 UTC, lejabque commented on shared_ptr.h
> +    }
Если cblock одинаковые, то указатель, из которого делали мув, останется нулевым, поэтому счетчик ссылок уменьшится на 1, как и должен

2020-09-27 21:36 UTC, lejabque commented on shared_ptr.h
> +    }
Если cblock одинаковые, то указатель, из которого делали мув, останется нулевым, поэтому счетчик ссылок уменьшится на 1, как и должен

2020-09-28 08:35 UTC, Dogzik approved these changes

2020-09-28 08:35 UTC, closed without merging