PR1
CPP-KT/shared_ptr_task pull request #6
Opened 2020-09-27 19:08 UTC by Dave11ar

2020-09-28 14:34 UTC, Dogzik requested changes

2020-09-28 14:34 UTC, Dogzik commented on control_block.h
> +  Deleter deleter;
Если `Deleter` пустой класс, который лишь содержит оператор `()`, то он будет занимать место в классе, хотя может этого не делать, если воспользоваться empty base optimization

2020-09-28 14:34 UTC, Dogzik commented on control_block.h
> +  not_init_block(T* p, Deleter d) : ptr(p), deleter(d) {}
А зачем тут копировать `d`?

2020-09-28 14:34 UTC, Dogzik commented on control_block.h
> +};
Перенос в конце файла

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +  }
Почему мы просто не переиспольовать конструктор ниже?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    control = new not_init_block<Y, Deleter>(static_cast<Y*>(p), d);
Зачем тут каст?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    ptr = static_cast<T*>(p);
[note] По смыслу тут должен быть каст наследника к базе, которые не обязательно делать явно

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    control = new not_init_block<std::nullptr_t, Deleter>(p, d);
Кажется `std::nullptr_t*` это не то, что ты хочешь хранить в блоке. Вообще этот конструктор не обязателен. А даже если обязателен ему нет причин выделять блок вообще

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr().swap(r);
Казалось бы ты уже в `r` на 46 строке поместил пустой `shred_ptr` и в этом свапе нет смысла

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +  shared_ptr(const shared_ptr<Y>& r) noexcept : control(r.control), ptr(static_cast<T*>(r.ptr)) {
Каст тут не обязателен, ибо как писалось выше каст наследнка к предку

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr<T>().swap(r);
Строчкой выше ты уже поместил в `r` пустой указатель. Зачем этот свап?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    ptr = r.ptr;
Почему бы просто не `shared_ptr(r).swap(*this)`?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    ptr = static_cast<T*>(r.ptr);
Почему бы просто не `shared_ptr(r).swap(*this)`?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr<T>(p).swap(*this);
Почему бы тут не переиспользовать более общий `reset`?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    shared_ptr<T>(p, d).swap(*this);
Зачем копировать `d`?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +}
Почему бы просто не сравнить с `nullptr` вместо этих странных кастов?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +  weak_ptr(const weak_ptr<Y>& r) noexcept : control(r.control), ptr(static_cast<T*>(r.ptr)) {
Тут каст не обязателен

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +  weak_ptr(const shared_ptr<Y>& r) noexcept : control(r.control), ptr(static_cast<T*>(r.ptr)) {
Тут каст не обязателен

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    weak_ptr<T>().swap(r);
Зачем этот свап, если свап выше уже поместил в `r` пустой `weak_ptr`?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +    weak_ptr<T>().swap(r);
Зачем этот свап, если свап выше уже поместил в `r` пустой `weak_ptr`?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +  long use_count() const noexcept {
`size_t`?

2020-09-28 14:34 UTC, Dogzik commented on shared_ptr.h
> +  long use_count() const noexcept {
`size_t`?

2020-09-28 16:37 UTC, Dave11ar commented on control_block.h
> +  Deleter deleter;
fixed

2020-09-28 16:38 UTC, Dave11ar commented on control_block.h
> +  not_init_block(T* p, Deleter d) : ptr(p), deleter(d) {}
fixed

2020-09-28 16:39 UTC, Dave11ar commented on control_block.h
> +};
fixed

2020-09-28 16:41 UTC, Dave11ar commented on shared_ptr.h
> +  }
fixed

2020-09-28 16:41 UTC, Dave11ar commented on shared_ptr.h
> +    control = new not_init_block<Y, Deleter>(static_cast<Y*>(p), d);
fixed

2020-09-28 16:46 UTC, Dave11ar commented on shared_ptr.h
> +    ptr = static_cast<T*>(p);
fixed

2020-09-28 16:46 UTC, Dave11ar commented on shared_ptr.h
> +    control = new not_init_block<std::nullptr_t, Deleter>(p, d);
fixed

2020-09-28 16:49 UTC, Dave11ar commented on shared_ptr.h
> +    shared_ptr().swap(r);
согласен, не осилил, что в this пустой указатель

2020-09-28 16:51 UTC, Dave11ar commented on shared_ptr.h
> +  shared_ptr(const shared_ptr<Y>& r) noexcept : control(r.control), ptr(static_cast<T*>(r.ptr)) {
fixed

2020-09-28 16:51 UTC, Dave11ar commented on shared_ptr.h
> +    shared_ptr<T>().swap(r);
fixed

2020-09-28 16:52 UTC, Dave11ar commented on shared_ptr.h
> +    ptr = r.ptr;
и правда

2020-09-28 16:53 UTC, Dave11ar commented on shared_ptr.h
> +    ptr = static_cast<T*>(r.ptr);
fixed

2020-09-28 16:54 UTC, Dave11ar commented on shared_ptr.h
> +    shared_ptr<T>(p).swap(*this);
fixed

2020-09-28 16:55 UTC, Dave11ar commented on shared_ptr.h
> +    shared_ptr<T>(p, d).swap(*this);
fixed

2020-09-28 16:57 UTC, Dave11ar commented on shared_ptr.h
> +  long use_count() const noexcept {
в `std::shared_ptr` было так, fixed

2020-09-28 16:57 UTC, Dave11ar commented on shared_ptr.h
> +  long use_count() const noexcept {
fixed

2020-09-28 16:58 UTC, Dave11ar commented on shared_ptr.h
> +}
fixed

2020-09-28 16:59 UTC, Dave11ar commented on shared_ptr.h
> +  weak_ptr(const weak_ptr<Y>& r) noexcept : control(r.control), ptr(static_cast<T*>(r.ptr)) {
fixed

2020-09-28 16:59 UTC, Dave11ar commented on shared_ptr.h
> +  weak_ptr(const shared_ptr<Y>& r) noexcept : control(r.control), ptr(static_cast<T*>(r.ptr)) {
fixed

2020-09-28 16:59 UTC, Dave11ar commented on shared_ptr.h
> +    weak_ptr<T>().swap(r);
fixed

2020-09-28 17:09 UTC, Dave11ar commented on shared_ptr.h
> +    weak_ptr<T>().swap(r);
fixed

2020-09-30 11:29 UTC, Dogzik commented on shared_ptr.h
> +    control = new not_init_block<Y, Deleter>(static_cast<Y*>(p), d);
Теперь если вылетит исключение, ты не вызовешь `d(p)`, хотя должен

2020-09-30 11:30 UTC, Dogzik commented on shared_ptr.h
> +    control = new not_init_block<std::nullptr_t, Deleter>(p, d);
Почему бы просто не перевызвать дефольный деструктор теперь?

2020-09-30 11:35 UTC, Dogzik commented on shared_ptr.h
> +}
Тут скорее вопрос стиля, что ли. Ты выражаешь бинарный оператор через унарный. Однако в любом случае ты используешь нежелательные сишные касты, а плюс

2020-09-30 11:39 UTC, Dogzik requested changes
Почитай комменты к прошлым тредам

2020-09-30 16:02 UTC, Dave11ar commented on shared_ptr.h
> +    control = new not_init_block<Y, Deleter>(static_cast<Y*>(p), d);
fixed

2020-09-30 16:03 UTC, Dave11ar commented on shared_ptr.h
> +    control = new not_init_block<std::nullptr_t, Deleter>(p, d);
fixed

2020-09-30 16:07 UTC, Dave11ar commented on shared_ptr.h
> +}
fixed

2020-09-30 20:41 UTC, Dogzik commented on shared_ptr.h
> +    control = new not_init_block<Y, Deleter>(static_cast<Y*>(p), d);
Теоретически прилететь может не только `bad_alloc`, а так же ты не пробрасываешь исключение наружу, а просто молча его съедаешь, вводя в ступор вызывающего

2020-09-30 20:42 UTC, Dogzik requested changes
Отписал о проблеме в старый тред

2020-09-30 20:42 UTC, closed without merging